apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-api-staging
  labels:
    app: flight-api
    environment: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flight-api
      environment: staging
  template:
    metadata:
      labels:
        app: flight-api
        environment: staging
    spec:
      containers:
      - name: flight-api
        image: ghcr.io/gilby125/flight-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: ENVIRONMENT
          value: "staging"
        - name: LOG_LEVEL
          value: "debug"
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
