services:
  api:
    image: ghcr.io/gilby125/flight-api:${IMAGE_TAG:-latest}
    build:
      context: .
    environment:
      # Build/version metadata (shown in Admin → Workers)
      APP_VERSION: ${IMAGE_TAG:-latest}

      PORT: 8080
      ENVIRONMENT: ${ENVIRONMENT:-production}
      WORKER_ENABLED: ${WORKER_ENABLED:-true}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: flights
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: flights
      DB_SSLMODE: ${DB_SSLMODE:-disable}
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_QUEUE_GROUP: ${REDIS_QUEUE_GROUP:-flights_workers}
      REDIS_QUEUE_STREAM_PREFIX: ${REDIS_QUEUE_STREAM_PREFIX:-flights}
      REDIS_QUEUE_BLOCK_TIMEOUT: ${REDIS_QUEUE_BLOCK_TIMEOUT:-5s}
      REDIS_QUEUE_VISIBILITY_TIMEOUT: ${REDIS_QUEUE_VISIBILITY_TIMEOUT:-2m}
    depends_on:
      - postgres
      - neo4j
      - redis
    # Removed host port mapping - Dokploy handles routing
    # ports:
    #   - "8080:8080"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    restart: unless-stopped
    # Swarm rolling update config for zero-downtime deployments
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 30s
        order: start-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 30s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: flights
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: flights
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flights"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}", "--save", "60", "1", "--loglevel", "warning"]
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "PING"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redisdata:/data
    restart: unless-stopped

  neo4j:
    image: neo4j:5
    environment:
      NEO4J_AUTH: neo4j/${NEO4J_PASSWORD}
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u neo4j -p ${NEO4J_PASSWORD} \"RETURN 1\""]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 40s
    volumes:
      - neo4jdata:/data
    restart: unless-stopped

volumes:
  pgdata:
  redisdata:
  neo4jdata:
