services:
  api:
    image: ghcr.io/gilby125/flight-api:${IMAGE_TAG:-latest}
    build:
      context: .
    environment:
      # Build/version metadata (shown in Admin → Workers)
      APP_VERSION: ${IMAGE_TAG:-latest}

      PORT: 8080
      ENVIRONMENT: ${ENVIRONMENT:-production}
      WORKER_ENABLED: ${WORKER_ENABLED:-true}
      # PostgreSQL (Internal Service)
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: flights
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: flights
      DB_SSLMODE: disable
      # Neo4j (Internal Service)
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
      # Redis (Internal Service)
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_QUEUE_GROUP: ${REDIS_QUEUE_GROUP:-flights_workers}
      REDIS_QUEUE_STREAM_PREFIX: ${REDIS_QUEUE_STREAM_PREFIX:-flights}
      REDIS_QUEUE_BLOCK_TIMEOUT: ${REDIS_QUEUE_BLOCK_TIMEOUT:-5s}
      REDIS_QUEUE_VISIBILITY_TIMEOUT: ${REDIS_QUEUE_VISIBILITY_TIMEOUT:-2m}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      neo4j-init:
        condition: service_completed_successfully
    # Removed host port mapping - Dokploy handles routing
    # ports:
    #   - "8080:8080"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    restart: unless-stopped
    # Swarm rolling update config for zero-downtime deployments
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 30s
        order: start-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 30s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: flights
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: flights
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flights"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}", "--save", "60", "1", "--loglevel", "warning"]
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "PING"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redisdata:/data
    restart: unless-stopped

  neo4j:
    image: neo4j:5
    environment:
      NEO4J_AUTH: neo4j/${NEO4J_PASSWORD}
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
    healthcheck:
      # Simple healthcheck for the process
      test: ["CMD-SHELL", "wget -q --spider http://localhost:7474 || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 40s
    volumes:
      - neo4jdata:/data
    restart: unless-stopped

  # Automated Neo4j Init Helper
  # This ensures the password matches NEO4J_PASSWORD even on existing volumes
  neo4j-init:
    image: neo4j:5
    depends_on:
      - neo4j
    command: >
      bash -c "
        echo 'Waiting for Neo4j Bolt to be ready...'
        until cypher-shell -u neo4j -p neo4j 'RETURN 1' >/dev/null 2>&1 || cypher-shell -u neo4j -p ${NEO4J_PASSWORD} 'RETURN 1' >/dev/null 2>&1; do
          sleep 5
        done
        echo 'Neo4j is up. Checking if password needs update...'
        if cypher-shell -u neo4j -p neo4j 'RETURN 1' >/dev/null 2>&1; then
          echo 'Default password detected. Updating to matches ${NEO4J_PASSWORD}...'
          cypher-shell -u neo4j -p neo4j \"ALTER CURRENT USER SET PASSWORD FROM 'neo4j' TO '${NEO4J_PASSWORD}'\"
          echo 'Password updated successfully.'
        else
          echo 'Password already updated or matches env var. All good.'
        fi
      "

volumes:
  pgdata:
  redisdata:
  neo4jdata:
