services:
  api:
    image: ghcr.io/gilby125/flight-api:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 8080
      ENVIRONMENT: production
      API_ENABLED: "true"
      WORKER_ENABLED: "true"
      INIT_SCHEMA: "true"
      SEED_NEO4J: "true"
      # DB Connectivity (Internal)
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: flights
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: flights
      DB_SSLMODE: disable
      # Redis Connectivity (Internal)
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      # Neo4j Connectivity (Internal)
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
    depends_on:
      - postgres
      - redis
      - neo4j
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "/app/flight-api", "-health-check"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flights-api.rule=Host(`${DOMAIN:-flights.local}`)"
      - "traefik.http.routers.flights-api.entrypoints=web"
      - "traefik.http.services.flights-api.loadbalancer.server.port=8080"
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: flights
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: flights
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flights"]
      interval: 10s
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}", "--save", "60", "1"]
    volumes:
      - redisdata:/data
    restart: unless-stopped

  neo4j:
    image: neo4j:5
    environment:
      NEO4J_AUTH: neo4j/${NEO4J_PASSWORD}
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:7474 || exit 1"]
      interval: 15s
    volumes:
      - neo4jdata:/data
    restart: unless-stopped

volumes:
  pgdata:
  redisdata:
  neo4jdata:
