services:
  api:
    image: ghcr.io/gilby125/flight-api:${IMAGE_TAG:-latest}
    environment:
      PORT: 8080
      ENVIRONMENT: production
      API_ENABLED: "true"
      WORKER_ENABLED: "true"
      INIT_SCHEMA: "true"
      SEED_NEO4J: "true"
      # DB Connectivity (Internal)
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: flights
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: flights
      DB_SSLMODE: disable
      # Redis Connectivity (Internal)
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      # Neo4j Connectivity (Internal)
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      neo4j-init:
        condition: service_completed_successfully
    # IMPORTANT: No host port binding here to avoid conflict with multi-replicas
    # Komodo handles routing to internal port 8080
    expose:
      - 8080
    healthcheck:
      test: ["CMD", "/app/flight-api", "-health-check"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: flights
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: flights
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flights"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}", "--save", "60", "1"]
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "PING"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redisdata:/data

  neo4j:
    image: neo4j:5
    environment:
      NEO4J_AUTH: neo4j/${NEO4J_PASSWORD}
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:7474 || exit 1"]
      interval: 15s
    volumes:
      - neo4jdata:/data

  neo4j-init:
    image: neo4j:5
    depends_on:
      - neo4j
    command: >
      bash -c "
        echo 'Waiting for Neo4j Bolt to be ready...'
        until cypher-shell -a bolt://neo4j:7687 -u neo4j -p neo4j 'RETURN 1' >/dev/null 2>&1 || cypher-shell -a bolt://neo4j:7687 -u neo4j -p ${NEO4J_PASSWORD} 'RETURN 1' >/dev/null 2>&1; do
          sleep 5
        done
        echo 'Neo4j is up. Checking if password needs update...'
        if cypher-shell -a bolt://neo4j:7687 -u neo4j -p neo4j 'RETURN 1' >/dev/null 2>&1; then
          echo 'Default password detected. Updating...'
          cypher-shell -a bolt://neo4j:7687 -u neo4j -p neo4j \"ALTER CURRENT USER SET PASSWORD FROM 'neo4j' TO '${NEO4J_PASSWORD}'\"
        else
          echo 'Password already set. All good.'
        fi
      "

volumes:
  pgdata:
  redisdata:
  neo4jdata:
