package main

import (
	"encoding/csv"
	"fmt"
	"os"
	"strings"
)

func escapeSQL(s string) string {
	return strings.ReplaceAll(s, "'", "''")
}

func main() {
	f, err := os.Open("./db/seed/airports.csv")
	if err != nil {
		fmt.Println("Error opening CSV:", err)
		return
	}
	defer f.Close()

	r := csv.NewReader(f)
	records, err := r.ReadAll()
	if err != nil {
		fmt.Println("Error reading CSV:", err)
		return
	}

	out, err := os.Create("./db/migrations/000003_seed_airports.sql")
	if err != nil {
		fmt.Println("Error creating migration file:", err)
		return
	}
	defer out.Close()

	out.WriteString(`-- Seed airports with full data from mwgg/Airports (Google Flights supported only)
-- Generated by db/seed/generate_migration.go
-- IDEMPOTENT: Uses ON CONFLICT DO UPDATE for safe re-runs

-- Add new columns if they don't exist
ALTER TABLE airports ADD COLUMN IF NOT EXISTS icao VARCHAR(4);
ALTER TABLE airports ADD COLUMN IF NOT EXISTS state VARCHAR(100);
ALTER TABLE airports ADD COLUMN IF NOT EXISTS elevation_ft INTEGER;
ALTER TABLE airports ADD COLUMN IF NOT EXISTS timezone VARCHAR(100);

-- Upsert all airports (3,429 Google Flights supported)
-- This is idempotent - safe to run multiple times
INSERT INTO airports (code, icao, name, city, state, country, latitude, longitude, elevation_ft, timezone) VALUES
`)

	for i, row := range records[1:] { // Skip header
		if i > 0 {
			out.WriteString(",\n")
		}
		out.WriteString(fmt.Sprintf("('%s', '%s', '%s', '%s', '%s', '%s', %s, %s, %s, '%s')",
			escapeSQL(row[0]), // iata
			escapeSQL(row[1]), // icao
			escapeSQL(row[2]), // name
			escapeSQL(row[3]), // city
			escapeSQL(row[4]), // state
			escapeSQL(row[5]), // country
			row[6],            // latitude
			row[7],            // longitude
			row[8],            // elevation_ft
			escapeSQL(row[9]), // timezone
		))
	}
	out.WriteString(`
ON CONFLICT (code) DO UPDATE SET
    icao = EXCLUDED.icao,
    name = EXCLUDED.name,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    country = EXCLUDED.country,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    elevation_ft = EXCLUDED.elevation_ft,
    timezone = EXCLUDED.timezone,
    updated_at = NOW();
`)
	fmt.Printf("Generated db/migrations/000003_seed_airports.sql with %d airports (idempotent)\n", len(records)-1)
}
