apiVersion: v1
kind: Secret
metadata:
  name: flight-api-certs
  labels:
    app: flight-api
type: kubernetes.io/tls
data:
  # Pre-generated TLS certificates (validate before applying)
  tls.crt: $(if [ -f tls/tls.crt ]; then cat tls/tls.crt | base64 -w0; else exit 1; fi)
  tls.key: $(if [ -f tls/tls.key ]; then cat tls/tls.key | base64 -w0; else exit 1; fi)
  ca.crt: $(if [ -f tls/ca.crt ]; then cat tls/ca.crt | base64 -w0; else exit 1; fi)
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  username: BASE64_POSTGRES_USER
  password: BASE64_POSTGRES_PASSWORD
